# Docker-compose for software_application smartretail
version: "3.5"

services:
  nginx:
    image: quay.io/cdis/nginx-igv:master
    container_name: nginx-gen3-igv
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data:/static-data
    ports:
      - ${SERVICE_PORT}:80
  gen3-igv:
    container_name: gen3-igv
    image: quay.io/cdis/gen3-igv:master
    restart: on-failure
    environment:
      # - APP_BASE_URL=http://localhost:4000
      - PROTOCOL=https
      - HOSTNAME=localhost
      - PORT=${SERVICE_PORT}
    volumes:
      - ${DATA_VOLUME}:/data
